version: '3.8'

services:
  app-boot:
    container_name: app-boot
    build:
      context: .
      dockerfile: ops/docker/Dockerfile  # Dockerfile 경로
    ports:
      - "8080:8080"
    depends_on:
      - app-mysql
      - app-redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://app-mysql:3306/api
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_REDIS_HOST: app-redis
      SPRING_REDIS_PORT: 6379
    networks:
      - app-network
    restart: always
    mem_limit: 256m  # 메모리 제한
    cpus: 0.5  # CPU 사용 제한

  app-mysql:
    container_name: app-mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: api
    volumes:
      - ./ops/docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - app-network
    mem_limit: 256m  # 메모리 제한
    cpus: 0.5  # CPU 사용 제한

  app-redis:
    container_name: app-redis
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-network
    mem_limit: 128m  # 메모리 제한
    cpus: 0.5  # CPU 사용 제한

networks:
  app-network:
    driver: bridge
