-- TABLE 생성
CREATE TABLE TB_BOARD (
    BOARD_ID NUMBER,
    TITLE VARCHAR2(300),
    CONTENT VARCHAR2(4000),
    REG_ID VARCHAR2(100),
    REG_DATE DATE DEFAULT SYSDATE
);

-- SEQUENCE
CREATE SEQUENCE SEQ_BOARD;