name: Deploy to EC2

on:
  push:
    branches:
      - main  # main 브랜치에 push 시 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build the project
        run: |
          ./gradlew build  # Gradle 빌드 실행 (JAR 파일 생성)

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          ssh -t ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            # 애플리케이션 디렉토리로 이동
            cd ~/myapp

            # 최신 코드로 업데이트
            git pull origin main

            # ops/docker 디렉토리로 이동
            cd ops/docker

            # 기존 Docker Compose 컨테이너 종료
            docker-compose down

            # Docker Compose로 새로 빌드 및 실행
            docker-compose up -d --build
          EOF
